backend:
  name: github
  branch: main
  repo: dgladmananshincare-png/docusaurus-feedback-example
  base_url: https://docusaurus-feedback-example.vercel.app
  auth_endpoint: /auth

publish_mode: editorial_workflow

# These lines should *not* be indented
media_folder: "static/img" # Media files will be stored in the repo under static/images/uploads
public_folder: "/img/" # The src attribute for uploaded media will begin with /images/uploads

display_url: https://docusaurus-feedback-example.vercel.app/
locale: "ja"

search: false

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

collections:
- name: folder1
  label: "Folder 1"
  folder: docs/folder1
  identifier_field: title
  extension: md
  widget: "list"
  create: true
  nested:
    depth: 5
    summary: "{{title}}"
  slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  fields:
    - { name: title, label: Title, widget: string }
    - { name: body, label: Body, widget: markdown }
    - { name: slug, label: Slug, widget: string }
  meta: { path: { widget: string, label: "Path", index_file: "_index" } }

- name: folder2
  label: "Folder 2"
  folder: docs/folder2
  identifier_field: title
  extension: md
  widget: "list"
  create: true
  nested:
    depth: 5
    summary: "{{title}}"
  slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  fields:
    - { name: title, label: Title, widget: string }
    - { name: body, label: Body, widget: markdown }
    - { name: slug, label: Slug, widget: string }
  meta: { path: { widget: string, label: "Path", index_file: "_index" } }